name: CI
on: { pull_request: { } }
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      prometheus_rules: ${{ steps.find_files.outputs.prometheus_rules }}
    steps:
      - uses: actions/checkout@v5
      - id: find_files
        run: |
          prometheus_rules=$(
            find prometheus/rules -iname '*.yml' -type f -exec basename {} \; | \
            jq -Rnc '[inputs | sub("\\.yml$"; "")]'
          )
          echo "prometheus_rules=${prometheus_rules}" >> $GITHUB_OUTPUT

  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: infrabits/ci-pack@main
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          builder: tools-harbor.wmcloud.org/toolforge/heroku-builder:24_0.20.7

  lint-prometheus-rules:
    runs-on: ubuntu-latest
    needs: [setup]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.setup.outputs.prometheus_rules) }}
    steps:
      - uses: actions/checkout@v5
      - run: |
          docker run \
            -v $PWD:/mnt \
            -w /mnt/prometheus/rules \
            --entrypoint=promtool \
            prom/prometheus \
            check rules \
            --lint=all \
            --lint-fatal \
            ${{ matrix.target }}.yml
